--Q1 .WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN. 
SELECT ENAME
FROM SCOTT.EMP
WHERE SAL >ALL(SELECT SAL
               FROM SCOTT.EMP
               WHERE JOB='SALESMAN');

-- Q2 WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE  CLERKS. 
SELECT *
FROM SCOTT.EMP
WHERE  HIREDATE >ALL(SELECT HIREDATE
                     FROM SCOTT.EMP
                     WHERE JOB='CLARK');  

 -- Q3 .WAQTD NAME AND SALARY FOR ALL THE EMPLOYEES IF THEY  ARE EARNING LESS THAN ATLEST A MANAGER   
 SELECT ENAME,SAL
 FROM SCOTT.EMP
 WHERE SAL<(SELECT MAX(SAL)
            FROM SCOTT.EMP
            WHERE SAL IN(SELECT SAL
                         FROM SCOTT.EMP
                         WHERE JOB='MANAGER')
            );  
  --  OR    
SELECT ENAME,SAL
FROM SCOTT.EMP
WHERE SAL< ANY(SELECT SAL
                FROM SCOTT.EMP
                WHERE JOB='MANAGER'
           );  

-- Q4 .WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS 
SELECT ENAME ,HIREDATE
FROM SCOTT.EMP
WHERE HIREDATE <ALL(SELECT HIREDATE
                    FROM SCOTT.EMP
                    WHERE JOB='MANAGER');  
-- Q5 WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS 
--DIFF ANSWER
SELECT ENAME
FROM SCOTT.EMP
WHERE HIREDATE > ALL(SELECT HIREDATE 
                     FROM SCOTT.EMP
                     WHERE JOB='MANAGER')
                AND SAL >ALL(SELECT SAL 
                     FROM SCOTT.EMP
                     WHERE JOB='CLARK')  ; 
 -- Q6 .WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEST A SALESMAN. 
 SELECT *
 FROM SCOTT.EMP
 WHERE job='CLERK' AND
       HIREDATE <ANY(SELECT HIREDATE 
                     FROM SCOTT.EMP
                     WHERE JOB='SALESMAN');
 -- Q7.WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT.                     
SELECT *
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE DNAME IN('ACCOUNTING','SALES'));

 -- Q8  .WAQTD DEPARTMENT NAMES OF THE EMPOYEES WITH NAME SMITH , KING AND MILLER.               
SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP
                WHERE ENAME IN('SMITH','KING','MILLER'));


 -- Q9 WAQTD DETAILS OF EMPLOYEES WORKING IN NEWYORK OR CHICAGO               
SELECT *
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO 
               FROM SCOTT.DEPT
               WHERE LOC IN('NEW YORK','CHICAGO'));


-- Q10 WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 10. 
-- DIFF ANS
SELECT ENAME
FROM SCOTT.EMP
WHERE HIREDATE >ALL(SELECT HIREDATE
                    FROM SCOTT.EMP
                     WHERE DEPTNO=10);


SELECT * FROM SCOTT.EMP;