--Q1 WAQTD ENAME, MNAME,ESAL,MSAL OF TOP 3 EMP BASED ON MANAGER SAL
SELECT *
FROM (
SELECT E.ENAME AS ENAMES,M.ENAME AS MNAMES,E.SAL AS ESAL,M.SAL AS MSAL 
FROM SCOTT.EMP E JOIN SCOTT.EMP M
ON E.MGR=M.EMPNO
ORDER BY MSAL DESC)
WHERE ROWNUM<=3;


-- Q2 WAQTD TOP 2 DNAME BASED ON THE NO OF EMPLOYEES
SELECT *
FROM(
SELECT COUNT(*) ,D.DNAME
FROM SCOTT.EMP E INNER JOIN SCOTT.DEPT D
ON E.DEPTNO=D.DEPTNO
GROUP BY D.DNAME
ORDER BY COUNT(*) DESC)
WHERE ROWNUM<=2;

-- Q3 WAQTD EMP NAME,MNAME,ESAL,MSAL, BASED ON THE MANAGER SALARY / WORST MANAGER TOP 2
-- Q4 WAQTD WORST EMP BASED ON SAL 
SELECT *
FROM(
SELECT *
FROM SCOTT.EMP
ORDER BY SAL ASC)
WHERE ROWNUM<=3;

-- Q5 NTH MAX NTH MIN USING PSEUDO COLUMN 
-- THIS APPROCH INCLUDS DUPLICATE RECORDS
SELECT * FROM 
(SELECT ROWNUM R,SCOTT.EMP.*
FROM SCOTT.EMP
ORDER BY SAL DESC)
WHERE R=1;

-- BY EXCLUDING DUPLICATE RECORDS
select sal
from(SELECT sal,rownum r
from(SELECT DISTINCT SAL
FROM SCOTT.EMP)
order by sal desc)
where r in(5,8,10);

-- Q6 WAQTD EXACTLY MIDDLE ROW OF EMP TABLE
SELECT *
FROM (SELECT ROWNUM R,SCOTT.EMP.*
      FROM SCOTT.EMP)
WHERE R=(SELECT COUNT(*)
FROM SCOTT.EMP)/2;

-- Q7 WAQTD EXACTLY MIDDLE ROW AND NEXT TWO ROWS
SELECT *
FROM (SELECT ROWNUM R ,SCOTT.EMP.*
      FROM SCOTT.EMP)
WHERE R IN((SELECT COUNT(*)
           FROM SCOTT.EMP)/2,(SELECT COUNT(*)
           FROM SCOTT.EMP)/2+1,(SELECT COUNT(*)
           FROM SCOTT.EMP)/2+2 )  ;    

-- Q8 WAQTD EXACTLY MIDDLE ROW, PREVIOUS ROW AND NEWT ROW
SELECT *
FROM (SELECT ROWNUM R, SCOTT.EMP.*
      FROM SCOTT.EMP)
WHERE R IN((SELECT COUNT(*)
           FROM SCOTT.EMP)/2,(SELECT COUNT(*)
                              FROM SCOTT.EMP)/2-1,(SELECT COUNT(*)
                                                   FROM SCOTT.EMP)/2+1);      



