-- Q1
SELECT ORDERID,CUSTOMERNAME,PRODUCTNAME,ORDERDATE
FROM (CUSTOMER C INNER JOIN `ORDER` O
ON C.CUSTOMERID=O.CUSTOMERID) INNER JOIN PRODUCT P
ON P.PRODUCTID=O.PRODUCTID;


-- Q2
SELECT CUSTOMERNAME,sum(QUANTITY)aS TOTAL
FROM (CUSTOMER C INNER JOIN `ORDER` O
ON C.CUSTOMERID=O.CUSTOMERID) INNER JOIN PRODUCT P
ON P.PRODUCTID=O.PRODUCTID
GROUP BY CUSTOMERNAME,QUANTITY;

-- Q3
SELECT CUSTOMERNAME,PRODUCTNAME
FROM (CUSTOMER C INNER JOIN `ORDER` O
ON C.CUSTOMERID=O.CUSTOMERID) INNER JOIN PRODUCT P
ON P.PRODUCTID=O.PRODUCTID
WHERE P.CATEGORY='Electronics';

-- 	Q4 
SELECT ORDERID,CUSTOMERNAME,PRODUCTNAME,(PRICE*QUANTITY)AS TOTALAMT
FROM (CUSTOMER C INNER JOIN `ORDER` O
ON C.CUSTOMERID=O.CUSTOMERID) INNER JOIN PRODUCT P
ON P.PRODUCTID=O.PRODUCTID
GROUP BY  ORDERID,CUSTOMERNAME,PRODUCTNAME,(PRICE*QUANTITY);

-- Q5

SELECT CUSTOMERNAME 
FROM CUSTOMER 
WHERE CUSTOMERID NOT IN(SELECT CUSTOMERID
                        FROM `ORDER`) ;
                        
               -- OR
SELECT CUSTOMERNAME
FROM CUSTOMER C LEFT OUTER JOIN `ORDER` O
ON C.CUSTOMERID=O.CUSTOMERID            
WHERE O.CUSTOMERID IS NULL;

-- Q6 
SELECT PRODUCTNAME,CUSTOMERNAME,O.*
FROM (CUSTOMER C INNER JOIN `ORDER` O
ON C.CUSTOMERID=O.CUSTOMERID) RIGHT OUTER JOIN PRODUCT P
ON P.PRODUCTID=O.PRODUCTID
WHERE P.PRODUCTID IS NULL;

-- Q7
SELECT PRODUCTNAME,CUSTOMERNAME
FROM (CUSTOMER C INNER JOIN `ORDER` O
ON C.CUSTOMERID=O.CUSTOMERID) INNER JOIN PRODUCT P
ON P.PRODUCTID=O.PRODUCTID
ORDER BY C.CUSTOMERNAME;
