-- Q1 WAQTD 5TH MIN AND 10TH MAX SAL
SELECT  SAL 
FROM (SELECT ROWNUM R ,SAL
      FROM (SELECT DISTINCT SAL
            FROM SCOTT.EMP
            ORDER BY SAL DESC))
WHERE R=(select COUNT(DISTINCT SAL)-4
               FROM SCOTT.EMP) OR R=10;
-- OR 
SELECT SAL
FROM (SELECT ROWNUM R,SAL
      FROM (SELECT DISTINCT SAL
            FROM SCOTT.EMP
            ORDER BY SAL DESC))
WHERE   R=10

UNION 
SELECT SAL
FROM (SELECT ROWNUM R,SAL
      FROM (SELECT DISTINCT SAL
            FROM SCOTT.EMP
            ORDER BY SAL ASC))
WHERE R=5;

-- Q2 WAQTD TOP 2 EMP IN EACH DEPARTMENT BASED ON THE SAL
SELECT *
FROM (SELECT DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS R ,SAL,DEPTNO
      FROM SCOTT.EMP)
WHERE R<=2;




