--Q1 WAQTD ENAME, DNAME of all the employees. 
SELECT ENAME,DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON SCOTT.EMP.DEPTNO=SCOTT.DEPT.DEPTNO;

-- Q2 WAQTD ENAME, SAL & LOC of all the employees. 
SELECT ENAME,SAL,LOC
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON SCOTT.EMP.DEPTNO=SCOTT.DEPT.DEPTNO;

-- Q3 WAQTD ENAME, DEPTNO & DNAME of all the employees
SELECT ENAME,DNAME,DEPT.DEPTNO
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT  
ON SCOTT.EMP.DEPTNO=SCOTT.DEPT.DEPTNO;

-- Q4 WAQTD ENAME, DEPTNO & DNAME of employees working in DEPTNO 20. 
SELECT ENAME,EMP.DEPTNO,DEPT.DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE SCOTT.EMP.DEPTNO=20;

--Q5 WAQTD ENAME, DNAME of employees who are earning less than Rs.2000
SELECT ENAME ,DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE SAL<2000;
--Q6 WAQTD ENAME, LOC of employees working in ‘DALLAS’
SELECT ENAME ,LOC
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE LOC IN ('DALLAS');

-- Q7 WAQTD ENAME, SAL & DNAME of employees whose name starts with character ‘A’ & DNAME ends with character ‘S
SELECT ENAME , SAL,DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=SCOTT.DEPT.DEPTNO
WHERE ENAME LIKE 'A%' AND ENAME LIKE '%S';

-- Q8  WAQTD ENAME, SAL, DNAME of all the employees who are earning more than ‘SCOTT’ in ‘ACCOUNTING’ department. 
SELECT ENAME,SAL,DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON DEPT.DEPTNO=EMP.DEPTNO
WHERE SAL>(SELECT SAL
           FROM SCOTT.EMP
           WHERE ENAME='SCOTT') AND
     DNAME='ACCOUNTING';     

-- Q9  WAQTD number of employees hired before ‘ALLEN’ in ‘RESEARCH’ department using joins. 
-- DIFF DEPT
SELECT COUNT(*)
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON DEPT.DEPTNO=EMP.DEPTNO
WHERE HIREDATE <(SELECT EMP.HIREDATE
                FROM SCOTT.EMP
                WHERE EMP.ENAME='ALLEN') AND
      EMP.DEPTNO IN (SELECT DEPT.DEPTNO 
                FROM SCOTT.DEPT
                WHERE DNAME='RESEARCH')          

-- Q10  WAQTD maximum SAL given to the employees working in same designation as that of ‘BLAKE’ in ‘DALLAS’
SELECT MAX(SAL)
FROM SCOTT.EMP
WHERE JOB IN (SELECT JOB 
              FROM SCOTT.EMP
              WHERE ENAME='BLAKE')
           AND DEPTNO IN(SELECT DEPTNO 
                         FROM SCOTT.DEPT
                         WHERE LOC = 'DALLAS')   

 -- Q11  WAQTD ENAME, HIREDATE & DNAME of employees hired in the month of ‘FEB’ & his DNAME must have second character as ‘A’.                        
SELECT ENAME , HIREDATE ,DEPT.DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON DEPT.DEPTNO = EMP.DEPTNO
WHERE HIREDATE LIKE '%FEB%' AND 
      DNAME LIKE '_A%';

-- Q12   WAQTD ENAME earning more than ‘MILLER’ in ‘NEW YORK’ using Both Sub-query & joins     
SELECT ENAME 
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE LOC ='NEW YORK' AND 
    SAL>(SELECT SAL
         FROM SCOTT.EMP
         WHERE ENAME='MILLER');
-- Q13    WAQTD ENAME & DNAME of employee who is having exactly 4 chracters in his name & his DNAME should have 2 consecutive 'CC       
SELECT ENAME,DEPT.DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMP.ENAME LIKE '____' AND DEPT.DNAME LIKE '%CC%'; 
         
-- Q14 WAQTD DNAME, ENAME & LOC of employees hired before 1981 in ‘DALLAS’.          
SELECT DEPT.DNAME,EMP.ENAME,DEPT.LOC
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMP.HIREDATE< '01-JAN-81' AND DEPT.LOC IN('DALLAS');

-- Q15 WAQTD ENAME, JOB, LOC of employees working in same designation as that of ‘JONES’ in ‘CHICAGO’.
SELECT EMP.ENAME,EMP.JOB,DEPT.LOC
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMP.JOB IN(SELECT JOB
                 FROM SCOTT.EMP
                 WHERE ENAME='JONES')
      AND DEPT.LOC='CHICAGO';           

 -- Q16 WAQTD ENAME, LOC of employees who is searching same SAL as that of ‘SCOTT‘ in ‘DALLAS’ & he was hired in the month of ‘DEC’     
 SELECT EMP.ENAME,DEPT.LOC
 FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
 ON EMP.DEPTNO=DEPT.DEPTNO
 WHERE EMP.SAL IN(SELECT SAL
                 FROM SCOTT.EMP
                 WHERE ENAME='SCOTT')
      AND DEPT.LOC='DALLAS' AND HIREDATE LIKE '%DEC%'; 

-- Q17  WAQTD ENAME, DNAME of employees whose designation ends with string ‘MAN’ & his name must have 2 consecutive ‘LL’     
SELECT EMP.ENAME,DEPT.DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO= DEPT.DEPTNO
WHERE EMP.JOB LIKE '%MAN'
     AND EMP.ENAME LIKE '%LL%';
-- 18  WAQTD ENAME, DEPTNO & DNAME of employees working in same designation as that of ‘SMITH’ in ‘NEW YORK’    
SELECT EMP.ENAME,DEPT.DEPTNO,DEPT.DNAME 
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMP.JOB IN(SELECT JOB
                 FROM SCOTT.EMP
                 WHERE ENAME='SMITH')
      AND DEPT.LOC='NEW YORK'; 

-- Q19 WAQTD ENAME & DNAME of employees hired after 1980 into ‘RESEARCH’ department & working as an ‘ANALYST’. 
-- DIFF ANSWER
SELECT EMP.ENAME,DEPT.DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT 
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMP.HIREDATE >'31-DEC-80' AND 
      DEPT.DNAME='RESEARCH' AND 
      EMP.JOB='ANALYST' ;
--Q20 WAQTD ENAME, SAL, LOC of employees whose SAL ends with 50 in ‘CHICAGO’ & his name must start with ‘M’ & ends with ‘N’.       
SELECT EMP.ENAME,EMP.SAL,DEPT.LOC
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE SAL LIKE '%50' AND
      DEPT.LOC='CHICAGO' AND 
      EMP.ENAME LIKE 'M%N';

-- Q21 WAQTD ENAME, DNAME of employees earning less than ‘JAMES’ & must be hired in the year 1980 in ‘DALLAS’.      
SELECT EMP.ENAME,DEPT.DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE SAL<(SELECT SAL
           FROM SCOTT.emp
           WHERE ENAME='JAMES')
      AND HIREDATE LIKE '%80'
      AND DEPT.LOC IN('DALLAS');     

 -- Q22 WAQTD ENAME & DEPTNO & DNAME of employees working as ‘SALESMAN’ or ‘MANAGER’ in DEPTNO 20 or 30 & he must be earning more than ‘WARD’ in ‘SALES’ or ‘RESEARCH’ department & he must get commission.     
 SELECT EMP.ENAME,EMP.DEPTNO,DEPT.DNAME
 FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
 ON EMP.DEPTNO=DEPT.DEPTNO
 WHERE (JOB='SALESMAN' OR JOB='MANAGER')
        AND EMP.DEPTNO IN(20,30)
        AND EMP.SAL>(SELECT SAL 
             FROM SCOTT.EMP
             WHERE ENAME='WARD')
        AND EMP.DEPTNO IN(SELECT DEPTNO 
                           FROM SCOTT.DEPT
                           WHERE DNAME IN('SALES','RESEARCH')    
        AND EMP.COMM IS NOT NULL);


-- Q23 WAQTD ENAME of the employees & their LOC of all the employees. 
SELECT EMP.ENAME , DEPT.LOC
FROM SCOTT.DEPT INNER JOIN SCOTT.EMP
ON EMP.DEPTNO=DEPT.DEPTNO;

--Q24 WAQTD DNAME & SAL for all the employee working in ‘ACCOUNTING‘ department. 
SELECT DEPT.DNAME,EMP.SAL
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON DEPT.DEPTNO=EMP.DEPTNO
WHERE DNAME='ACCOUNTING';

--Q25 WAQTD DNAME & ANNUALSAL for all employees whose SAL is more than Rs.2340. 
SELECT DEPT.DNAME, (EMP.SAL*12) AS ANNUALSAL
FROM SCOTT.DEPT INNER JOIN SCOTT.EMP
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMP.SAL>2340;

-- Q26 WAQTD ENAME & DNAME for employees having character ‘A’ in their DNAME. 
SELECT EMP.ENAME,DEPT.DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE DEPT.DNAME LIKE '%A%';

-- Q27 WAQTD ENAME & DNAME for all the employees working as ‘SALESMAN’.
SELECT EMP.ENAME ,DEPT.DNAME
FROM SCOTT.DEPT INNER JOIN SCOTT.emp
ON EMP.DEPTNO = DEPT.DEPTNO 
WHERE EMP.JOB='SALESMAN';

-- Q28 WAQTD ENNAME, DNAME & JOB for all the employees whose JOB & DNAME starts with character ‘S’
SELECT EMP.ENAME,DEPT.DNAME,EMP.JOB
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON DEPT.DEPTNO = EMP.DEPTNO
WHERE JOB LIKE 'S%' AND DNAME LIKE 'S%';

-- Q29 WAQTD ENAME, DNAME & MGR for employees reporting to 7839. 
SELECT EMP.ENAME,DEPT.DNAME,EMP.MGR 
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON DEPT.DEPTNO=EMP.DEPTNO
WHERE EMPNO IN(SELECT EMPNO  
               FROM SCOTT.EMP
               WHERE MGR=7839);

-- Q30  WAQTD ENAME, DNAME & HIREDATE for employees hired after 83 into ‘ACCOUNTING’ or ‘RESEARCH’ department.               
SELECT EMP.ENAME,DEPT.DNAME,EMP.HIREDATE
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE HIREDATE>'31-DEC-83'
 AND DEPT.DNAME IN('ACCOUNTING','RESEARCH');

 -- Q31  WAQTD ENAME, DNAME, COMMISSION & DEPTNO of the employees who are getting COMM in DEPTNO 10 or 30. 
 SELECT EMP.ENAME,DEPT.DNAME,EMP.COMM,EMP.DEPTNO
 FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
 ON EMP.DEPTNO = DEPT.DEPTNO 
 WHERE EMP.DEPTNO IN(10,30) AND
       EMP.COMM IS NOT NULL;

-- Q32 WAQTD DNAME & EMPNO for all the employees whose EMPNO are (7839, 7902) & are working in LOC = ‘NEW YORK’       
SELECT DEPT.DNAME,EMP.EMPNO
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON EMP.DEPTNO =DEPT.DEPTNO
WHERE EMP.EMPNO IN(7839,7902) AND DEPT.LOC ='NEW YORK';

-- Q33  WAQTD ENAME & DNAME who are earning more than ‘SMITH’
SELECT EMP.ENAME,DEPT.DNAME
FROM SCOTT.EMP INNER JOIN SCOTT.DEPT
ON DEPT.DEPTNO=EMP.DEPTNO
WHERE SAL>(SELECT SAL
          FROM SCOTT.EMP
          WHERE ENAME='SMITH');

