-- LIMIT CLAUSE : LIMIT CLAUSE IS USED TO DUSPLAY THE RANGE AND SHOW THE RESULT
-- TGHIS LIMIT CLAUSE DON'T SUPPORT IN ORACLE DATABASE BUT IT SUPPORT IN MYSQL AND POSTGRESQL

-- Q1 WAQTD TOP 5 BEST EMP IN THE COMPANY BASED ON THE SALARY 
-- SELECT *
-- FROM SCOTT.EMP
-- ORDER BY SAL DESC
-- LIMIT 5;

-- Q2 WAQTD EXACTLY 5TH HIGHEST SALARY 
SELECT SAL
FROM SCOTT.EMP
ORDER BY SAL DESC
LIMIT 4,1;

-- OR IN CASE OF DUPLICATE SAL WE CAN USE DISTINCT CLAUSE
SELECT DISTINCT(SAL)
FROM SCOTT.EMP
ORDER BY SAL DESC
LIMIT 4,1;

--Q2 WAQTD 10TH MIN SAL
SELECT DISTINCT(SAL)
FROM SCOTT.EMP 
ORDER BY SAL DESC
LIMIT 9,1 -- <= HERE THE 9 IS USED A LIMIT TO EXCLUDE THE NUMBER OF ROW FURST AND THEN 1 IS USED AS A IFF SET TO SELECT THE 1 ROW 

-- Q3 WAQTD TOP 10 RECORDS FROM TABLE
SELECT *
FROM SCOTT.EMP
LIMIT 10;

-- Q4 WAQTD EXACTLY 10 TH AND 11 TH HIGHEST SAL
SELECT *
FROM SCOTT.EMP
ORDER BY SAL DESC
LIMIT 9,2;





