--Q1  WAQTD SMITH'S REPORTING MANAGER NAME. 
sELECT ENAME
fROM SCOTT.EMP
WHERE EMPNO IN(SELECT MGR
               FROM SCOTT.EMP
               WHERE ENAME='SMITH');

-- Q2 WAQTD MILLER'S MANAGER'S SALARY. 
SELECT SAL
FROM SCOTT.EMP
WHERE EMPNO IN(SELECT MGR
               FROM SCOTT.EMP
               WHERE ENAME='MILLER')               
 -- Q3 WAQTD ALLEN'S MANAGER NAME.
 SELECT ENAME 
 FROM SCOTT.EMP
 WHERE EMPNO IN(SELECT MGR 
                 FROM SCOTT.EMP
                 WHERE ENAME='ALLEN');
--Q4  WAQTD SALARY OF ADAMS MANAGER. 
SELECT SAL
FROM SCOTT.EMP
WHERE EMPNO IN(SELECT MGR  
               FROM SCOTT.EMP
               WHERE ENAME='ADAMS');

-- Q5 WAQTD NAME OF ADAM'S MANAGER'S MANAGER.
SELECT ENAME
FROM SCOTT.EMP
WHERE EMPNO IN(SELECT MGR 
               FROM SCOTT.EMP
               WHERE EMPNO IN(SELECT MGR
                              FROM SCOTT.EMP
                              WHERE ENAME='ADAMS' ));
-- Q6 WAQTD LOCATION OF SMITH'S MANAGER'S MANAGER. 
SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO 
                FROM SCOTT.EMP
                WHERE EMPNO IN(SELECT MGR
                               FROM SCOTT.EMP
                               WHERE EMPNO IN(SELECT MGR 
                                              FROM SCOTT.EMP
                                              WHERE ENAME='SMITH')));

-- Q7 WAQTD NUMBER OF EMP'S REPORTING TO KING 
SELECT COUNT(*)
FROM SCOTT.EMP
WHERE MGR IN(SELECT EMPNO
               FROM SCOTT.EMP
               WHERE ENAME='KING');

--- Q8 WAQTD NAME OF AN EMP REPORTING TO BLAKE. 
SELECT ENAME
FROM SCOTT.EMP
WHERE MGR IN(SELECT EMPNO 
             FROM SCOTT.EMP
             WHERE ENAME='BLAKE');
 --Q9  WAQTD DETAILS OF AN EMP REPORTING TO JONES
 SELECT *
 FROM SCOTT.EMP
 WHERE MGR IN(SELECT EMPNO
              FROM SCOTT.EMP
              WHERE ENAME='JONES');   
 -- Q10 WAQTD LOCATION OF MARTIN'S MANAGER
 SELECT LOC,DNAME
 FROM SCOTT.DEPT
 WHERE DEPTNO IN(SELECT DEPTNO 
                 FROM SCOTT.EMP
                 WHERE EMPNO IN(SELECT MGR 
                                 FROM SCOTT.EMP
                                 WHERE ENAME='MARTIN')); 

 --Q11   WAQTD NUMBER OF EMP'S REPORTING TO FORD. 
 SELECT COUNT(*)
 FROM SCOTT.EMP
 WHERE MGR IN(SELECT EMPNO 
              FROM SCOTT.EMP 
              WHERE ENAME='FORD')  ;                             
-- Q12  WAQTD COMMISION OF BLAKE'S MANAGER'S MANAGER. 
SELECT COMM
FROM SCOTT.EMP
WHERE EMPNO IN(SELECT MGR
               FROM SCOTT.EMP
               WHERE EMPNO IN(SELECT MGR
                              FROM SCOTT.EMP
                              WHERE ENAME='BLAKE'));

 -- Q13   WAQTD DEPARTMENT NAME OF CLARK'S MANAGER. 
SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP
                WHERE EMPNO IN(SELECT MGR 
                                FROM SCOTT.EMP
                                WHERE ENAME='CLARK'))    ;    
 -- Q14 WAQTD LOCATION OF SCOTT'S MANAGER
 SELECT LOC
 FROM SCOTT.DEPT
 WHERE DEPTNO IN(SELECT DEPTNO
                 FROM SCOTT.EMP
                 WHERE EMPNO IN(SELECT MGR FROM 
                                SCOTT.EMP
                                WHERE ENAME='SCOTT'));
 -- Q15   WAQTD DEPTNO OF MILLER'S MANAGER.
 SELECT DEPTNO 
 FROM SCOTT.EMP
 WHERE EMPNO IN(SELECT MGR
                FROM SCOTT.EMP
                WHERE ENAME='MILLER');      
 -- Q16  WAQTD TOTAL SALARY GIVEN TO WARD'S MANAGER'S DEPTNO 
 SELECT SUM(SAL)
 FROM SCOTT.EMP
 WHERE DEPTNO IN(SELECT DEPTNO
                 FROM SCOTT.EMP
                 WHERE EMPNO IN(SELECT MGR
                                 FROM SCOTT.EMP
                                 WHERE ENAME='WARD'));
 -- Q17 WAQTD MINIMUM SALARY GIVEN TO TURNER'S MANAGER'S DEPTNO                                
SELECT MIN(SAL)
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP
                WHERE EMPNO IN(SELECT MGR
                               FROM SCOTT.EMP
                               WHERE ENAME='TURNER'));
 --- Q18 WAQTD AVERAGE SALARY GIVEN TO JONE'S MANAGER'S DEPTNO 
 SELECT AVG(SAL)
 FROM SCOTT.EMP
 WHERE DEPTNO IN(SELECT DEPTNO
                 FROM SCOTT.EMP
                 WHERE EMPNO  IN(SELECT MGR
                                  FROM SCOTT.EMP
                                  WHERE ENAME='JONES'));    

 -- Q19 WAQTD NUMBER OF EMP'S PRESENT IN JAMES MANAGER'S DEPTNO.
 SELECT  COUNT(*)
 FROM SCOTT.EMP
 WHERE DEPTNO  IN(SELECT DEPTNO
                  FROM SCOTT.EMP
                  WHERE EMPNO IN(SELECT MGR
                                 FROM SCOTT.EMP
                                 WHERE ENAME='JAMES'));       
  -- Q20  WAQTD FIRST FIVE RECORDS FROM EMP TABLE.
  
  SELECT *
  FROM(SELECT SCOTT.EMP.*, ROW_NUMBER() OVER(ORDER BY EMPNO ASC) AS ROWSS
  FROM SCOTT.EMP)T
  WHERE T.ROWSS<=5;
    

    SELECT * FROM SCOTT.EMP;           