-- Number single row function
--1. MOD Function

-- EXAMPLES
SELECT MOD(5,2) FROM DUAL;

SELECT MOD(30,7) FROM DUAL;

--2. SQRT(ARG1)
-- EXAMPLES
SELECT SQRT(4) FROM DUAL;

SELECT SQRT(45) FROM DUAL;

SELECT SQRT(89) from dual;

--3. POWER()
select POWER(3,2) FROM DUAL;

SELECT POWER(7,3),POWER(90,2),POWER(9,2),POWER(45,3) FROM DUAL;

SELECT POWER(4,3), POWER(3,1) FROM DUAL;

--4. ABS: used to make neg value to positive

SELECT ABS(-232) FROM DUAL;

SELECT ABS(-32) FROM DUAL;

SELECT ABS(-432) FROM DUAL;

-- Q WAQTD ALL THE DETAILS OF EMPLOYEE IF THEY ARE GETTING EVEN SALARY 
SELECT *
FROM SCOTT.EMP
WHERE MOD(SAL,2)=0;

-- Q WAQTD ALL THE DETAILS OF EMPLOYEE IF THEY ARE GETTING ODD SALARY 
SELECT *
FROM SCOTT.EMP
WHERE MOD(SAL,2)=0;

-- Q WAQTD ENAME AND SAL CHECK IF FIRST DIGIT OF SALARY IS EVEN 
SELECT *
FROM SCOTT.EMP
WHERE MOD(SUBSTR(SAL,1,1),2)=0;

-- 5. ROUND FUNCTION : AFTER DECIMAL POINT HOW MANY DIGIT WE WANT

SELECT ROUND(788.33,1) FROM DUAL;

SELECT ROUND(34.544,0) FROM DUAL;

SELECT ROUND(34.434,1) FROM DUAL;

SELECT ROUND(-323.333,-1) FROM DUAL;

SELECT ROUND(-323.333,-2) FROM DUAL;

SELECT ROUND(-323.333,-3) FROM DUAL;

SELECT ROUND(-35.333,-1) FROM DUAL; -->40 

SELECT ROUND(-23.333,-1) FROM DUAL; --> 20


-- 6 TRUNC : IT IS A FUCTION USED TO REMOVE THE DECIMAL VALUE WITHOUT ROUNDING

SELECT TRUNC(474.838049) FROM DUAL;

SELECT TRUNC(472.838049) FROM DUAL;