--Q1 WAQTD NO OF EMP HIRED AFTER 'CLARK' AND WORKING IN DALLAS AND ACCOUNTING
select COUNT(*)
FROM SCOTT.EMP
WHERE HIREDATE<(SELECT HIREDATE 
                FROM SCOTT.EMP
                WHERE ENAME='CLARK') AND
      DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE LOC='DALLAS' OR DNAME='ACCOUNTING');            

-- Q2 WAQTD DETAILS OF EMP WITH ANNUAL SAL IF THE ANNUAL
-- SAL IS AT MOST 50,000 RS , THE EMP SHOULD WORK EITHER 
--IN RESEARCH OR SALES DEPT , THE EMP SAL SHOULD BE MORE THEN JAMES
SELECT SCOTT.EMP.*,12*SAL AS ANNUAL_SAL
FROM SCOTT.EMP
WHERE 12*SAL<=50000 AND 
      SAL>(SELECT SAL
           FROM SCOTT.EMP
           WHERE ENAME='JAMES') AND
      DEPTNO IN(SELECT DEPTNO 
                FROM SCOTT.DEPT
                WHERE DNAME IN('RESEARCHER','SALES'));     


-- Q3 WAQTD THE MAX SAL IN EACH JOB EXCEPT THE EMPLOYEE WORKIMG IN CHICAGO SORTED BY MAX SAL IN MIN TO MAX ORDER
SELECT MAX(SAL),JOB
FROM SCOTT.EMP
WHERE DEPTNO NOT IN (SELECT DEPTNO 
                    FROM SCOTT.DEPT
                    WHERE LOC IN('CHICAGO') )
GROUP BY JOB
ORDER BY MAX(SAL)     


--- Q4 WAQTD THE LOCATION IN DESC ORDER IF THERE ARE ATLEAST FOUR EMP WORKINGIN IN THE RESPECTIVE LOCATION
SELECT LOC
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP
                GROUP BY DEPTNO 
                HAVING COUNT(*)>=4);
ORDER BY LOC DESC;    

-- Q5 WAQTD THE DEPT_NAME IN WHICH THREE EMP ARE WORKING
SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO
               FROM SCOTT.EMP
               GROUP BY DEPTNO
               HAVING COUNT(*)=3);
-- Q6 WAQTD NO OF EMP AND AVG(SAL) IN EACH DESIGNATION AND DEPTNO IF THERE ARE AT LEAST ONE EMP 
-- PRESENT IN THE RESPECTIVE AREA SORTED BY GROUP BY EXP, EMP SHOULD HIRED AFTER SMITH BUT BEFORE 
---ADAM EXCEPT THE EMP OF THE LOCATION WHERE THREE EMP ARE WORKING
SELECT COUNT(*),AVG(SAL)
FROM SCOTT.EMP
WHERE HIREDATE >(SELECT HIREDATE
                 FROM SCOTT.EMP
                 WHERE ENAME='SMITH') AND
      HIREDATE <(SELECT HIREDATE
                FROM SCOTT.EMP
                WHERE ENAME='ADAM')AND
      DEPTNO NOT IN(SELECT DEPTNO 
                FROM SCOTT.EMP
                GROUP BY DEPTNO
                HAVING COUNT(*)=3);
GROUP BY JOB ,DEPTNO
ORDER BY  JOB ,DEPTNO;         

--- Q7 WAQTD DEPARTMENT NAME OF EMP WHOSE DESIGNATION IS PRESIDENT
SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP 
                WHERE JOB ='PRESIDENT');

--- Q8 WAQTD EMPLOYEE NAME OF EMP WORKING IN ACCOUNTING DEPARTMENT
SELECT ENAME
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE DNAME='ACCOUNTING');

---- Q9] WAQTD EMPLOYEE NAME & SALARY OF EMP'S WHO ARE WORKING IN CHICAGO
SELECT ENAME ,SAL
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO 
                FROM SCOTT.DEPT
                WHERE LOC='CHICAGO')
-- Q10 WAQTD DETAILS OF AN EMP WHOSE WORKING IN SALES DEPARTMENT
SELECT *
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO 
                FROM SCOTT.DEPT
                WHERE DNAME='SALES');  
-- Q11  WAQTD DETAILS OF EMP ALONG WITH ANNULAL SAL IF EMP'S ARE WORKING IN NEW YORK.   
 SELECT SCOTT.EMP.*,12*SAL AS ANNUAL_SAL
 FROM SCOTT.EMP
 WHERE DEPTNO IN(SELECT DEPTNO
                 FROM SCOTT.DEPT
                 WHERE LOC='NEW YORK');    
--Q12  WAQTD EMPLOYEE NAME OF EMP WORKING IN OPERATIONS DEPARTMENT.                                        
SELECT ENAME
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO 
                FROM SCOTT.DEPT
                WHERE DNAME='OPERATIONS');

-- Q13   WAQTD NAME OF EMP EARNING MORE THAN SCOTT IN ACCOUNTING DEPARTMENT.               
SELECT ENAME
FROM SCOTT.EMP
WHERE SAL>(SELECT SAL
           FROM SCOTT.EMP
           WHERE ENAME='SCOTT') 
           AND DEPTNO IN(SELECT DEPTNO 
                        FROM SCOTT.DEPT
                        WHERE DNAME='ACCOUNTING' );

-- Q14 WAQTD DETAILS OF EMP WORKING AS MANAGER IN CHICAGO. 
SELECT *
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.DEPT
                WHERE LOC='CHICAGO')
      AND JOB='MANAGER'; 
-- Q15   WAQTD NAME & SALARY OF EMP'S EARNING MORE THAN KING IN ACCOUNTING DEPARTMENT              
SELECT ENAME ,SAL
FROM SCOTT.EMP
WHERE SAL>(SELECT SAL
           FROM SCOTT.EMP
           WHERE ENAME='KING')
      AND DEPTNO IN(SELECT DEPTNO 
                    FROM SCOTT.DEPT
                    WHERE DNAME='ACCOUNTING');   
-- Q16  WAQTD DETAILS OF EMP WHO IS WORKING AS SALESMAN IN SALES DEPARTMENT                     
SELECT *
FROM SCOTT.EMP
WHERE JOB='SALESMAN' AND DEPTNO IN(SELECT DEPTNO 
                                   FROM SCOTT.DEPT
                                   WHERE DNAME='SALES');
-- Q17   WAQTD NAME, SAL, JOB, HIREDATE OF EMP'S WORKING IN OPERATION DEPARTMENT & HIRED BEFORE KING.                                  
SELECT ENAME,SAL,JOB,HIREDATE 
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO 
               FROM SCOTT.DEPT
               WHERE DNAME='OPERATION')
      AND HIREDATE<(SELECT HIREDATE 
                   FROM SCOTT.EMP
                  WHERE ENAME='KING');

--- Q18  WAQTD ALL THE EMP'S WHOSE DEPARTMENT NAME ENDING WITH 'S'. ENAME
SELECT ENAME
FROM SCOTT.EMP
WHERE DEPTNO IN(SELECT DEPTNO 
                FROM SCOTT.DEPT
                WHERE DNAME LIKE '%S');

-- Q19   WAQTD DEPARTMENT NAME OF EMP'S WHOSE SAL IS 800. 
SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP
                WHERE SAL=800)
-- Q20 WAQTD DNAME & LOC OF EMP'S WHOSE NAME HAS CHARACTER 'A' IN IT.
-- 14 DIFF ANSWER (HW)
SELECT LOC,DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO 
                FROM SCOTT.EMP
                WHERE ENAME LIKE '%A%');
-- Q21 WAQTD DEPT NAME OF AN EMP WHO EARNS COMMISSION. 
-- Q15 DIFF OUTPUT
SELECT DNAME
FROM SCOTT.DEPT
WHERE DEPTNO IN(SELECT DEPTNO
                FROM SCOTT.EMP
                WHERE COMM IS NOT NULL);
 --- Q22 WAQTD LOC OF EMP IF THEY EARN COMMISSION IN DEPARTMENT NUMBER 40              
 SELECT LOC
 FROM SCOTT.DEPT
 WHERE DEPTNO IN(SELECT DEPTNO 
                 FROM SCOTT.EMP
                 WHERE DEPTNO=40 AND COMM IS NULL);

-- Q23 WAQTD NAME OF THE EMP EARNING MAX SAL. 
SELECT ENAME
FROM SCOTT.EMP
WHERE SAL =(SELECT MAX(SAL)
               FROM SCOTT.EMP);              