-- BEST TWO EMP LOC BASED ON NUMBER EMP IN LOC
SELECT LOC
FROM (SELECT LOC, DENSE_RANK() OVER(ORDER BY R DESC) AS R
FROM(SELECT LOC,COUNT(*) R
     FROM SCOTT.EMP E INNER JOIN SCOTT.DEPT D
     ON E.DEPTNO=D.DEPTNO
     GROUP BY LOC))
WHERE R<=2 ;